services:
  watchtower:
    image: containrrr/watchtower
    command:
      - '--label-enable'
      - '--interval'
      - '30'
      - '--rolling-restart'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always 
    networks:
      - default

  reverse-proxy:
    image: traefik:v3.1
    command:
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=web'
      - '--entryPoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=chris@chrisnowicki.dev'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always 
    networks:
      - web
      - default

  portfolio:
    image: ghcr.io/chris-nowicki/portfolio-2.0:prod
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portfolio.rule=Host(`selfhost.chrisnowicki.dev`)'
      - 'traefik.http.routers.portfolio.entrypoints=websecure'
      - 'traefik.http.routers.portfolio.tls.certresolver=myresolver'
      - 'traefik.http.services.portfolio.loadbalancer.server.port=8080'
      - 'com.centurylinklabs.watchtower.enable=true'
    environment:
      - PUBLIC_CLOUDINARY_CLOUD_NAME="ddetibihn"
      - HOME=/tmp
      - NPM_CONFIG_CACHE=/tmp/.npm
      # Removed NODE_EXTRA_CA_CERTS since the path doesn't exist
    volumes:
      - node_cache:/tmp/.npm
    deploy:
      mode: replicated
      replicas: 3
    restart: always
    networks:
      - web
      - default

volumes:
  letsencrypt:
  node_cache:

networks:
  web:
    external: true
  default: